export type QuebecExercise = {
  id: string;
  category: string;
  phrase: string;
  prompt: string;
  choices: string[];
  answer: string;
  fr: string;
  en: string;
  register: string;
  examSafe: boolean;
  source: { title: string; url: string };
};
const usito = (word: string) => ({
  title: `Usito · ${word.replace("_2", "")}`,
  url: `https://usito.usherbrooke.ca/définitions/${word}`,
});
const sacres = {
  title: "Usito · Les sacres en français québécois, Diane Vincent",
  url: "https://usito.usherbrooke.ca/articles/thématiques/vincent_1",
};
const oral = {
  title: "Québec · Francisation, transcription de français parlé",
  url: "https://referencesfrancisation.immigration-quebec.gouv.qc.ca/moodle_ref/pluginfile.php/34516/mod_resource/content/1/N7_PO_S-03_films_Trans.pdf",
};
function entry(
  category: string,
  id: string,
  phrase: string,
  prompt: string,
  choices: string[],
  correct: number,
  fr: string,
  en: string,
  source: QuebecExercise["source"],
  register = "Familier",
  examSafe = false,
): QuebecExercise {
  return {
    category,
    id,
    phrase,
    prompt,
    choices,
    answer: choices[correct],
    fr,
    en,
    source,
    register,
    examSafe,
  };
}
// Original teaching examples; links credit the language reference, not a quoted speaker.
export const quebecExercises: QuebecExercise[] = [
  entry(
    "parle",
    "chu",
    "Chu prêt pour la promenade.",
    "Que signifie « chu » ?",
    ["Je cherche", "Je suis", "Je peux"],
    1,
    "« Chu » représente « je suis » à l’oral. À l’écrit standard : Je suis prêt pour la promenade.",
    "“Chu” is a spoken contraction of “je suis” (I am).",
    oral,
  ),
  entry(
    "parle",
    "pis",
    "On prend un café, pis on part.",
    "Quel mot relie les deux actions ici ?",
    ["Mais", "Sans", "Et"],
    2,
    "Ici, « pis » relie deux actions comme « et ». On prend un café, et on part.",
    "Here, “pis” connects two actions like “and”.",
    oral,
  ),
  entry(
    "parle",
    "chu-sens",
    "Chu devant le cinéma.",
    "Où est la personne ?",
    ["Devant le cinéma", "Dans le métro", "Elle ne le sait pas"],
    0,
    "Déplie le début : « Je suis devant le cinéma. » Reconnaître la contraction aide à suivre la phrase.",
    "Expand the start: “I am in front of the cinema.”",
    oral,
  ),
  entry(
    "parle",
    "pis-suite",
    "Je prends mes clés, pis mon manteau.",
    "Quelle version garde le même sens ?",
    [
      "Je prends mes clés sans mon manteau.",
      "Je prends mes clés et mon manteau.",
      "Je cherche mon manteau.",
    ],
    1,
    "« Pis » se comprend ici comme « et ». Le contexte indique que la personne prend les deux objets.",
    "Here “pis” means “and”: the person takes both objects.",
    oral,
  ),
  entry(
    "expressions",
    "pantoute",
    "Ça ne me dérange pas pantoute.",
    "Est-ce que cela dérange la personne ?",
    ["Beaucoup", "Un peu", "Pas du tout"],
    2,
    "« Pantoute » renforce la négation. Ici : cela ne me dérange absolument pas.",
    "“Pantoute” reinforces the negative: it does not bother me at all.",
    usito("pantoute"),
  ),
  entry(
    "expressions",
    "tanne",
    "Je suis tanné de ce bruit.",
    "Que ressent la personne ?",
    ["Elle en a assez.", "Elle aime ce bruit.", "Elle a froid."],
    0,
    "Dans cet emploi familier, « tanné » exprime l’impatience : la personne en a assez.",
    "Here “tanné” means fed up, not simply physically tired.",
    usito("tanné"),
  ),
  entry(
    "expressions",
    "misere",
    "J’ai de la misère à ouvrir ce pot.",
    "Quelle est la difficulté ?",
    ["Acheter le pot", "Ouvrir le pot", "Trouver le pot"],
    1,
    "« Avoir de la misère à » signifie ici avoir du mal à faire quelque chose.",
    "“Avoir de la misère à” means to have trouble doing something.",
    usito("misère"),
  ),
  entry(
    "expressions",
    "plate",
    "Cette émission est plate.",
    "Comment la personne trouve-t-elle l’émission ?",
    ["Passionnante", "Trop courte", "Ennuyeuse"],
    2,
    "Dans ce contexte, « plate » veut dire ennuyeuse. Dans une autre situation, le mot peut aussi exprimer une déception.",
    "Here “plate” means boring. In another context it can express disappointment.",
    usito("plate_2"),
  ),
  entry(
    "sacres",
    "sacre-origine",
    "Tabarnak !",
    "De quel domaine vient ce sacre ?",
    [
      "Du vocabulaire religieux",
      "Du vocabulaire sportif",
      "Du vocabulaire météo",
    ],
    0,
    "Ce sacre vient de « tabernacle ». Son emploi comme exclamation est vulgaire.",
    "This swear word comes from “tabernacle”, a religious term.",
    sacres,
    "Vulgaire · sacre",
  ),
  entry(
    "sacres",
    "sacre-registre",
    "Câlisse !",
    "Quel registre faut-il reconnaître ?",
    ["Neutre", "Vulgaire", "Administratif"],
    1,
    "« Câlisse » est une forme de sacre issue de « calice ». Ce n’est pas une formule neutre.",
    "This is a swear word derived from “calice”, not a neutral expression.",
    sacres,
    "Vulgaire · sacre",
  ),
  entry(
    "sacres",
    "sacre-contexte",
    "Un sacre éclate dans une conversation.",
    "Que faut-il observer pour comprendre l’émotion ?",
    [
      "Le nombre de lettres",
      "Seulement le dictionnaire",
      "Le ton et la situation",
    ],
    2,
    "Un sacre porte une forte charge expressive. Le ton et la situation aident à interpréter l’émotion.",
    "Tone and context help you interpret the emotion behind a swear word.",
    sacres,
    "Vulgaire · contexte",
  ),
  entry(
    "sacres",
    "sacre-choix",
    "Tu écris une demande formelle.",
    "Quelle formulation convient ?",
    ["Je suis très mécontent de ce retard.", "Câlisse !", "Tabarnak !"],
    0,
    "Pour cette demande, exprime le mécontentement sans sacre.",
    "For this formal request, express your dissatisfaction without swearing.",
    sacres,
    "Choix du registre",
  ),
  entry(
    "standard",
    "standard-chu",
    "Chu prêt.",
    "Quelle version choisir dans un devoir standard ?",
    ["Chu est prêt.", "Je suis prêt.", "Je prêt."],
    1,
    "Développe la contraction : « je suis ». Le sens reste le même.",
    "Use the full form “je suis” in standard writing.",
    oral,
  ),
  entry(
    "standard",
    "standard-pantoute",
    "Je ne comprends pas pantoute.",
    "Quelle version emploie un registre neutre ?",
    [
      "Je comprends tout.",
      "Je comprends peut-être.",
      "Je ne comprends pas du tout.",
    ],
    2,
    "« Du tout » remplace le familier « pantoute » sans changer le sens de la négation.",
    "“Du tout” replaces the informal “pantoute” while preserving the negative meaning.",
    usito("pantoute"),
  ),
  entry(
    "standard",
    "standard-depanneur",
    "Je vais au dépanneur.",
    "Faut-il éviter « dépanneur » parce que le mot est québécois ?",
    [
      "Non, c’est un mot standard au Québec.",
      "Oui, c’est un sacre.",
      "Oui, c’est toujours une faute.",
    ],
    0,
    "« Dépanneur » désigne notamment un petit commerce de quartier. Cet emploi est officialisé par l’OQLF : québécois ne veut pas dire incorrect.",
    "“Dépanneur” is a standard Québec word for a convenience store. Regional does not mean incorrect.",
    usito("dépanneur"),
    "Standard au Québec",
    true,
  ),
  entry(
    "standard",
    "standard-tanne",
    "Je suis tanné de recommencer.",
    "Quelle reformulation garde l’idée d’impatience ?",
    [
      "Je suis heureux de recommencer.",
      "J’en ai assez de recommencer.",
      "Je veux recommencer.",
    ],
    1,
    "La personne exprime son agacement. Il ne s’agit pas simplement d’avoir sommeil.",
    "The speaker is fed up, rather than simply sleepy.",
    usito("tanné"),
  ),
];
export const practiceCategories = [
  "parle",
  "expressions",
  "sacres",
  "standard",
];
export const beltRanks = [
  "Ceinture nouée croche",
  "Premier fil",
  "Motif simple",
  "Motif rouge dangereux",
  "Ceinture de survivant",
  "Ceinture d’archive",
  "Ceinture fléchée complète",
];
